Set up hello microverse project
d4nQw3rty/Hello-Microverse- pull request #1
Opened 2022-06-29 15:15 UTC by d4nQw3rty

2022-06-29 16:25 UTC, chrystalme requested changes
## Hi @Danys Linares, 

You have done a good job so far!
However, there are some issues that you still need to work on to prepare your project for further evaluation
## Highlights 💡 
✔️ Good Git commit messages
✔️ README looks professional
## Suggested changes ♻️ 
❌ Linters triggering workflows actions. Linters not set up properly.
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Also, you can reach me on [Twitter](https://twitter.com/afam_ifeanyi) or [Slack](https://microverse-community.slack.com/team/U019ZC99KFA). Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 16:25 UTC, chrystalme commented on README.md
> +- LinkedIn: [LinkedIn](https://www.linkedin.com/in/danys-linares-6a328b238?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BnkyI5IMjTzSg4PVJIZh%2BMw%3D%3D)
Kindly customise the to reflect your identity. Example, `GitHub: [@d4nQw3rty](https://github.com/d4nQw3rty)` which would look like GitHub: [@d4nQw3rty](https://github.com/d4nQw3rty)

2022-06-29 16:25 UTC, chrystalme commented on test.md
> +# "This file should be ignored by git".
Kindly include the following file in `.gitignore` so that they are not pushed to github: 
 - `node_modules/`
 - `test.md`

2022-06-29 16:25 UTC, chrystalme commented on .gitignore
> +node_modules/
Kindly include the following file in `.gitignore` so that they are not pushed to github: 
 - `node_modules/`
 - `test.md`

2022-06-29 16:25 UTC, chrystalme commented on .github/workflows/linters.yml
> +jobs:
Linters is not triggering workflows action to test your code-base. I think linters is not properly set up. Kindly check and make sure your linters is properly setup.

2022-06-29 18:06 UTC, Ismailco approved these changes
### Hi @d4nQw3rty,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 18:06 UTC, Ismailco commented on README.md
> +- Twitter: [@twitterhandle](https://twitter.com/Danys_Linares)
- [ ] [Optional] Kindly use your twitter handle instead of the place holder `@twitterhandle`, e.g: `Twitter: [@Danys_Linares](https://twitter.com/Danys_Linares)`

2022-06-29 18:06 UTC, Ismailco commented on README.md
> +- Twitter: [@twitterhandle](https://twitter.com/Danys_Linares)
- [ ] [Optional] Your PR doesn't have a description, kindly add a descriptive description to the PR so it summarize the changes inside the Pull Request

2022-06-29 18:45 UTC, merged

2022-07-04 15:18 UTC, prolajumokeoni reviewed
Hi @d4nQw3rty, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a wrong pull request that does not have the setup and mobile skeleton portfolio  version

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._